import type { ErrorObject } from "ajv";
const validate: {
  (data: unknown) : boolean;
  errors: ErrorObject[] | null;
}
export default validate;
// This file is auto-generated by the validateSchemaPlugin.