import { describe, test, expect } from "vitest";
import { makeTestSystemData } from "./makeSystemEx";
import type { Data_System } from "./system";

const expected = {
  advanced: {
    fallbackFonts: "",
    fontSize: 28,
    gameId: 0,
    mainFontFilename: "",
    numberFontFilename: "",
    picturesUpperLimit: 100,
    screenHeight: 0,
    screenScale: 1,
    screenWidth: 0,
    uiAreaHeight: 0,
    uiAreaWidth: 0,
    windowOpacity: 0,
  },
  airship: {
    bgm: {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    characterIndex: 0,
    characterName: "image",
    startMapId: 0,
    startX: 0,
    startY: 0,
  },
  armorTypes: ["text", "text"],
  attackMotions: [],
  battleBgm: {
    name: "audio",
    pan: 0,
    pitch: 100,
    volume: 90,
  },
  battleSystem: 0,
  battleback1Name: "",
  battleback2Name: "",
  battlerHue: 0,
  battlerName: "",
  boat: {
    bgm: {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    characterIndex: 0,
    characterName: "image",
    startMapId: 0,
    startX: 0,
    startY: 0,
  },
  currencyUnit: "text",
  defeatMe: {
    name: "audio",
    pan: 0,
    pitch: 100,
    volume: 90,
  },
  editMapId: 0,
  editor: {
    jsonFormatLevel: 0,
    messageWidth1: 816,
    messageWidth2: 816,
  },
  elements: ["text", "text"],
  equipTypes: ["text", "text"],
  faceSize: 144,
  gameTitle: "text",
  gameoverMe: {
    name: "audio",
    pan: 0,
    pitch: 100,
    volume: 90,
  },
  iconSize: 32,
  itemCategories: [true, true, true, true],
  locale: "en-US",
  magicSkills: [],
  menuCommands: [true, true, true, true, true, true],
  optAutosave: true,
  optDisplayTp: true,
  optDrawTitle: true,
  optExtraExp: true,
  optFloorDeath: true,
  optFollowers: true,
  optKeyItemsNumber: true,
  optMessageSkip: true,
  optSideView: true,
  optSlipDeath: true,
  optSplashScreen: true,
  optTransparent: true,
  partyMembers: [],
  ship: {
    bgm: {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    characterIndex: 0,
    characterName: "image",
    startMapId: 0,
    startX: 0,
    startY: 0,
  },
  skillTypes: ["text", "text"],
  sounds: [
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
    {
      name: "audio",
      pan: 0,
      pitch: 100,
      volume: 90,
    },
  ],
  startMapId: 0,
  startX: 0,
  startY: 0,
  switches: ["switches", "switches"],
  terms: {
    basic: [
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
    ],
    commands: [
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "",
      "text",
      "text",
      "",
      "text",
      "text",
    ],
    messages: {
      actionFailure: "text",
      actorDamage: "text",
      actorDrain: "text",
      actorGain: "text",
      actorLoss: "text",
      actorNoDamage: "text",
      actorNoHit: "text",
      actorRecovery: "text",
      alwaysDash: "text",
      autosave: "text",
      bgmVolume: "text",
      bgsVolume: "text",
      buffAdd: "text",
      buffRemove: "text",
      commandRemember: "text",
      counterAttack: "text",
      criticalToActor: "text",
      criticalToEnemy: "text",
      debuffAdd: "text",
      defeat: "text",
      emerge: "text",
      enemyDamage: "text",
      enemyDrain: "text",
      enemyGain: "text",
      enemyLoss: "text",
      enemyNoDamage: "text",
      enemyNoHit: "text",
      enemyRecovery: "text",
      escapeFailure: "text",
      escapeStart: "text",
      evasion: "text",
      expNext: "text",
      expTotal: "text",
      file: "text",
      levelUp: "text",
      loadMessage: "text",
      magicEvasion: "text",
      magicReflection: "text",
      meVolume: "text",
      obtainExp: "text",
      obtainGold: "text",
      obtainItem: "text",
      obtainSkill: "text",
      partyName: "text",
      possession: "text",
      preemptive: "text",
      saveMessage: "text",
      seVolume: "text",
      substitute: "text",
      surprise: "text",
      touchUI: "text",
      useItem: "text",
      victory: "text",
    },
    params: [
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
      "text",
    ],
  },
  testBattlers: [],
  testTroopId: 0,
  tileSize: 48,
  title1Name: "image",
  title2Name: "image",
  titleBgm: {
    name: "audio",
    pan: 0,
    pitch: 100,
    volume: 90,
  },
  titleCommandWindow: {
    background: 0,
    offsetX: 0,
    offsetY: 0,
  },
  variables: ["variables", "variables"],
  versionId: 1,
  victoryMe: {
    name: "audio",
    pan: 0,
    pitch: 100,
    volume: 100,
  },
  weaponTypes: ["text", "text"],
  windowTone: [0, 0, 0, 0],
};
describe("makeTestSystemData", () => {
  test("returns expected structure", () => {
    const result: Data_System = makeTestSystemData({
      audio: "audio",
      image: "image",
      text: "text",
      switches: "switches",
      variables: "variables",
    });
    expect(result).toEqual(expected);
  });
});
