import { makeAudioFileParams } from "@RpgTypes/libs";
import type { System_SoundsObject } from "./core";
import {
  convertTermsMessageMZtoMV,
  createMenuCommandState,
  makeParamNamesFromArray,
  makeSoundsObject,
  makeTermsBasicFromArray,
  makeTermsCommandFromArray,
  makeVehicleData,
} from "./core";
import { makeSystemData } from "./makeSystem";
import type { Data_System } from "./system";
import type { Data_SystemMV } from "./systemMV";
import type { SystemTestDataSource } from "./types/testDataSoruce";

export const makeSystemDataMV = (
  data: Data_System = makeSystemData({}),
): Data_SystemMV => {
  return {
    versionId: data.versionId,
    menuCommands: data.menuCommands,
    locale: data.locale,
    startMapId: data.startMapId,
    startX: data.startX,
    startY: data.startY,
    partyMembers: data.partyMembers,
    magicSkills: data.magicSkills,
    title1Name: data.title1Name,
    title2Name: data.title2Name,
    gameTitle: data.gameTitle,
    currencyUnit: data.currencyUnit,
    windowTone: data.windowTone,
    battleback1Name: data.battleback1Name,
    battleback2Name: data.battleback2Name,
    testTroopId: data.testTroopId,
    testBattlers: data.testBattlers,
    attackMotions: data.attackMotions,
    battlerHue: data.battlerHue,
    battlerName: data.battlerName,
    airship: data.airship,
    boat: data.boat,
    ship: data.ship,
    defeatMe: data.defeatMe,
    gameoverMe: data.gameoverMe,
    optDisplayTp: data.optDisplayTp,
    optDrawTitle: data.optDrawTitle,
    optExtraExp: data.optExtraExp,
    optFloorDeath: data.optFloorDeath,
    optSideView: data.optSideView,
    optFollowers: data.optFollowers,
    optSlipDeath: data.optSlipDeath,
    optTransparent: data.optTransparent,
    skillTypes: data.skillTypes,
    weaponTypes: data.weaponTypes,
    armorTypes: data.armorTypes,
    elements: data.elements,
    equipTypes: data.equipTypes,
    switches: data.switches,
    variables: data.variables,
    titleBgm: data.titleBgm,
    battleBgm: data.battleBgm,
    victoryMe: data.victoryMe,
    editMapId: data.editMapId,
    sounds: data.sounds,
    terms: {
      basic: data.terms.basic,
      commands: data.terms.commands,
      params: data.terms.params,
      messages: convertTermsMessageMZtoMV(data.terms.messages),
    },
  };
};

export const makeSystemDataFromMV = (data: Data_SystemMV): Data_System => {
  return makeSystemData({
    versionId: data.versionId,

    menuCommands: createMenuCommandState(data),
    locale: data.locale,
    gameInit: {
      startMapId: data.startMapId,
      startX: data.startX,
      startY: data.startY,
      partyMembers: data.partyMembers,
    },
    battle: { magicSkills: data.magicSkills },
    bgm: {
      titleBgm: data.titleBgm,
      battleBgm: data.battleBgm,
    },
    options: data,
    vehicles: {
      airship: data.airship,
      boat: data.boat,
      ship: data.ship,
    },
    images: { title1Name: data.title1Name, title2Name: data.title2Name },
    me: {
      defeatMe: data.defeatMe,
      gameoverMe: data.gameoverMe,
      victoryMe: data.victoryMe,
    },
    battleTest: {
      battleback1Name: data.battleback1Name,
      battleback2Name: data.battleback2Name,
      testTroopId: data.testTroopId,
      testBattlers: data.testBattlers,
    },
    attackMotion: data.attackMotions,
    sounds: makeSoundsObject(data.sounds),
    dataNames: {
      skillTypes: data.skillTypes,
      weaponTypes: data.weaponTypes,
      armorTypes: data.armorTypes,
      elements: data.elements,
      equipTypes: data.equipTypes,
      switches: data.switches,
      variables: data.variables,
    },
    texts: {
      currencyUnit: data.currencyUnit,
      gameTitle: data.gameTitle,
    },
    editorTemporary: {
      editMapId: data.editMapId,
      battlerName: data.battlerName,
      battlerHue: data.battlerHue,
    },
    terms: {
      basic: makeTermsBasicFromArray(data.terms.basic),
      commands: makeTermsCommandFromArray(data.terms.commands),
      params: makeParamNamesFromArray(data.terms.params),
      messages: data.terms.messages,
    },
  });
};

export const makeTestSystemData = ({
  audio,
  image,
  text,
  switches,
  variables,
}: SystemTestDataSource): Data_System => {
  return makeSystemData({
    me: {
      defeatMe: makeAudioFileParams({ name: audio, volume: 90, pitch: 100 }),
      gameoverMe: makeAudioFileParams({ name: audio, volume: 90, pitch: 100 }),
      victoryMe: makeAudioFileParams({ name: audio, volume: 100, pitch: 100 }),
    },
    dataNames: {
      armorTypes: [text, text],
      equipTypes: [text, text],
      elements: [text, text],
      skillTypes: [text, text],
      weaponTypes: [text, text],
      switches: [switches, switches],
      variables: [variables, variables],
    },
    bgm: {
      titleBgm: makeAudioFileParams({ name: audio, volume: 90, pitch: 100 }),
      battleBgm: makeAudioFileParams({ name: audio, volume: 90, pitch: 100 }),
    },
    vehicles: {
      airship: makeVehicleData({
        bgm: makeAudioFileParams({ name: audio, volume: 90, pitch: 100 }),
        characterName: image,
      }),
      boat: makeVehicleData({
        bgm: makeAudioFileParams({ name: audio, volume: 90, pitch: 100 }),
        characterName: image,
      }),
      ship: makeVehicleData({
        bgm: makeAudioFileParams({ name: audio, volume: 90, pitch: 100 }),
        characterName: image,
      }),
    },
    images: {
      title1Name: image,
      title2Name: image,
    },
    texts: {
      gameTitle: text,
      currencyUnit: text,
    },
    terms: {
      basic: {
        exp: text,
        experience: text,
        hp: text,
        mp: text,
        hpA: text,
        mpA: text,
        level: text,
        levelA: text,
        tp: text,
        tpA: text,
      },
      messages: {
        actionFailure: text,
        actorDamage: text,
        actorDrain: text,
        actorGain: text,
        actorLoss: text,
        actorNoDamage: text,
        actorNoHit: text,
        actorRecovery: text,
        alwaysDash: text,
        autosave: text,
        bgmVolume: text,
        bgsVolume: text,
        buffAdd: text,
        buffRemove: text,
        commandRemember: text,
        criticalToActor: text,
        criticalToEnemy: text,
        counterAttack: text,
        debuffAdd: text,
        defeat: text,
        escapeFailure: text,
        emerge: text,
        evasion: text,
        expNext: text,
        expTotal: text,
        file: text,
        enemyDamage: text,
        enemyDrain: text,
        enemyGain: text,
        enemyLoss: text,
        enemyNoDamage: text,
        enemyNoHit: text,
        enemyRecovery: text,
        escapeStart: text,
        levelUp: text,
        possession: text,
        saveMessage: text,
        loadMessage: text,
        surprise: text,
        victory: text,
        magicEvasion: text,
        magicReflection: text,
        preemptive: text,
        meVolume: text,
        useItem: text,
        obtainExp: text,
        obtainGold: text,
        obtainItem: text,
        obtainSkill: text,
        partyName: text,
        touchUI: text,
        seVolume: text,
        substitute: text,
      },
      params: {
        agi: text,
        atk: text,
        def: text,
        mat: text,
        mdf: text,
        luk: text,
        eva: text,
        hit: text,
        mhp: text,
        mmp: text,
      },
      commands: {
        armor: text,
        item: text,
        skill: text,
        equip: text,
        status: text,
        formation: text,
        options: text,
        save: text,
        gameEnd: text,
        cancel: text,
        attack: text,
        guard: text,
        buy: text,
        sell: text,
        escape: text,
        clear: text,
        newGame: text,
        toTitle: text,
        continueGame: text,
        equip2: text,
        fight: text,
        keyItem: text,
        optimize: text,
        weapon: text,
      },
    },
    sounds: makeSoundsEx(audio),
  });
};

const makeSoundsEx = (audio: string): System_SoundsObject => {
  const audioData = makeAudioFileParams({
    name: audio,
    volume: 90,
    pitch: 100,
  });
  return {
    cursor: audioData,
    actorCollapse: audioData,
    actorDamage: audioData,
    battleStart: audioData,
    buzzer: audioData,
    enemyAttack: audioData,
    bossCollapes1: audioData,
    bossCollapes2: audioData,
    enemyCollapse: audioData,
    enemyDamage: audioData,
    escape: audioData,
    playEvasion: audioData,
    playMagicEvasion: audioData,
    playMiss: audioData,
    playRecovery: audioData,
    save: audioData,
    shop: audioData,
    cancel: audioData,
    useItem: audioData,
    useSkill: audioData,
    load: audioData,
    equip: audioData,
    ok: audioData,
    playReflection: audioData,
  };
};
