import type { Data_CommonEvent } from "@RpgTypes/rmmz/events";
import type { Data_Tileset } from "@RpgTypes/rmmz/rpg";
import type { Direction8 } from "@RpgTypes/rmmz/utils";
import type { Rmmz_Event, Rmmz_Map, Rmmz_Vehicle } from "./core";

export declare class Game_Map implements Rmmz_Map {
  initialize(): void;
  setup(mapId: number): void;
  isEventRunning(): boolean;
  tileWidth(): number;
  tileHeight(): number;
  bushDepth(): number;
  mapId(): number;
  tilesetId(): number;
  displayX(): number;
  displayY(): number;
  parallaxName(): string;
  battleback1Name(): string;
  battleback2Name(): string;
  requestRefresh(): void;
  isNameDisplayEnabled(): boolean;
  disableNameDisplay(): void;
  enableNameDisplay(): void;
  createVehicles(): void;
  refereshVehicles(): void;
  vehicles(): void;
  vehicle(type: string | number): Rmmz_Vehicle | null;
  boat(): Rmmz_Vehicle;
  ship(): Rmmz_Vehicle;
  airship(): Rmmz_Vehicle;
  setupEvents(): void;
  events(): Rmmz_Event[];
  event(eventId: number): Rmmz_Event | undefined;
  eraseEvent(eventId: number): void;
  autorunCommonEvents(): Data_CommonEvent[];
  parallelCommonEvents(): Data_CommonEvent[];
  setupScroll(): void;
  setupParallax(): void;
  setupBattleback(): void;
  setDisplayPos(x: number, y: number): void;
  parallaxOx(): number;
  parallaxOy(): number;
  tileset(): Data_Tileset;
  tilesetFlags(): [];
  displayName(): string;
  width(): number;
  height(): number;
  data(): [];
  isLoopHorizontal(): boolean;
  isLoopVertical(): boolean;
  isDashDisabled(): boolean;
  encounterList(): [];
  encounterStep(): number;
  isOverworld(): boolean;
  screenTileX(): number;
  screenTileY(): number;
  adjustX(x: number): number;
  adjustY(y: number): number;
  roundX(x: number): number;
  roundY(y: number): number;
  xWithDirection(x: number, d: Direction8): number;
  yWithDirection(y: number, d: Direction8): number;
  roundXWithDirection(x: number, d: Direction8): number;
  roundYWithDirection(y: number, d: Direction8): number;
  deltaX(x1: number, x2: number): number;
  deltaY(y1: number, y2: number): number;
  distance(x1: number, y1: number, x2: number, y2: number): number;
  canvasToMapX(x: number): number;
  canvasToMapY(y: number): number;
  autoplay(): void;
  refreshIfNeeded(): void;
  refresh(): void;
  refreshTileEvents(): void;
  eventsXy(x: number, y: number): Rmmz_Event[];
  eventsXyNt(x: number, y: number): Rmmz_Event[];
  tileEventsXy(x: number, y: number): Rmmz_Event[];
  eventIdXy(x: number, y: number): number;
  scrollDown(distance: number): void;
  scrollLeft(distance: number): void;
  scrollRight(distance: number): void;
  scrollUp(distance: number): void;
  isValid(x: number, y: number): boolean;
  checkPassage(x: number, y: number, bit: number): boolean;
  tileId(x: number, y: number, z: number): number;
  layeredTiles(x: number, y: number): [];
  allTiles(x: number, y: number): [];
  autotileType(x: number, y: number, z: number): number;
  isPassable(x: number, y: number, d: number): boolean;
  isBoatPassable(x: number, y: number): boolean;
  isShipPassable(x: number, y: number): boolean;
  isAirshipLandOk(x: number, y: number): boolean;
  checkLayeredTilesFlags(x: number, y: number, bit: number): boolean;
  isLadder(x: number, y: number): boolean;
  isBush(x: number, y: number): boolean;
  isCounter(x: number, y: number): boolean;
  isDamageFloor(x: number, y: number): boolean;
  terrainTag(x: number, y: number): number;
  regionId(x: number, y: number): number;
  startScroll(direction: number, distance: number, speed: number): void;
  isScrolling(): boolean;
  update(sceneActive: boolean): void;
  updateScroll(): void;
  scrollDistance(): number;
  doScroll(direction: number, distance: number): void;
  updateEvents(): void;
  updateVehicles(): void;
  updateParallax(): void;
  changeTileset(tilesetId: number): void;
  changeBattleback(battleback1Name: null, battleback2Name: null): void;
  changeParallax(
    name: string,
    loopX: boolean,
    loopY: boolean,
    sx: number,
    sy: number,
  ): void;
  updateInterpreter(): void;
  unlockEvent(eventId: number): void;
  setupStartingEvent(): boolean;
  setupTestEvent(): boolean;
  setupStartingMapEvent(): boolean;
  setupAutorunCommonEvent(): boolean;
  isAnyEventStarting(): boolean;
}
