import type { Terms_MessagesMV } from "@RpgTypes/rmmz";
import type { JSONSchemaType } from "ajv";

const SCHEMA_STRING = {
  type: "string",
} as const satisfies JSONSchemaType<string>;

export const SCHEMA_SYSTEM_TERMS_MESSAGES_MV = {
  type: "object",
  additionalProperties: false,
  required: [
    "actionFailure",
    "actorDamage",
    "actorDrain",
    "actorGain",
    "actorLoss",
    "actorNoDamage",
    "actorNoHit",
    "actorRecovery",
    "alwaysDash",
    "bgmVolume",
    "bgsVolume",
    "buffAdd",
    "buffRemove",
    "commandRemember",
    "counterAttack",
    "criticalToActor",
    "criticalToEnemy",
    "debuffAdd",
    "defeat",
    "emerge",
    "enemyDamage",
    "enemyDrain",
    "enemyGain",
    "enemyLoss",
    "enemyNoDamage",
    "enemyNoHit",
    "enemyRecovery",
    "escapeFailure",
    "escapeStart",
    "evasion",
    "expNext",
    "expTotal",
    "file",
    "levelUp",
    "loadMessage",
    "magicEvasion",
    "magicReflection",
    "meVolume",
    "obtainExp",
    "obtainGold",
    "obtainItem",
    "obtainSkill",
    "partyName",
    "possession",
    "preemptive",
    "saveMessage",
    "seVolume",
    "substitute",
    "surprise",
    "useItem",
    "victory",
  ] satisfies (keyof Terms_MessagesMV)[],
  properties: {
    actionFailure: SCHEMA_STRING,
    actorDamage: SCHEMA_STRING,
    actorNoDamage: SCHEMA_STRING,
    actorRecovery: SCHEMA_STRING,
    actorGain: SCHEMA_STRING,
    actorLoss: SCHEMA_STRING,
    actorDrain: SCHEMA_STRING,
    alwaysDash: SCHEMA_STRING,
    bgmVolume: SCHEMA_STRING,
    bgsVolume: SCHEMA_STRING,
    commandRemember: SCHEMA_STRING,
    criticalToActor: SCHEMA_STRING,
    criticalToEnemy: SCHEMA_STRING,
    counterAttack: SCHEMA_STRING,
    debuffAdd: SCHEMA_STRING,
    defeat: SCHEMA_STRING,
    enemyDamage: SCHEMA_STRING,
    enemyNoDamage: SCHEMA_STRING,
    enemyRecovery: SCHEMA_STRING,
    enemyGain: SCHEMA_STRING,
    enemyLoss: SCHEMA_STRING,
    enemyDrain: SCHEMA_STRING,
    evasion: SCHEMA_STRING,
    expNext: SCHEMA_STRING,
    expTotal: SCHEMA_STRING,
    escapeFailure: SCHEMA_STRING,
    escapeStart: SCHEMA_STRING,
    file: SCHEMA_STRING,
    loadMessage: SCHEMA_STRING,
    meVolume: SCHEMA_STRING,
    magicEvasion: SCHEMA_STRING,
    magicReflection: SCHEMA_STRING,
    obtainExp: SCHEMA_STRING,
    obtainGold: SCHEMA_STRING,
    obtainItem: SCHEMA_STRING,
    obtainSkill: SCHEMA_STRING,
    partyName: SCHEMA_STRING,
    preemptive: SCHEMA_STRING,
    saveMessage: SCHEMA_STRING,
    seVolume: SCHEMA_STRING,
    substitute: SCHEMA_STRING,
    victory: SCHEMA_STRING,
    useItem: SCHEMA_STRING,
    buffAdd: SCHEMA_STRING,
    buffRemove: SCHEMA_STRING,
    actorNoHit: SCHEMA_STRING,
    enemyNoHit: SCHEMA_STRING,
    emerge: SCHEMA_STRING,
    levelUp: SCHEMA_STRING,
    possession: SCHEMA_STRING,
    surprise: SCHEMA_STRING,
  },
} as const satisfies JSONSchemaType<Terms_MessagesMV>;
