import type { ErrorObject } from "ajv";
declare const validate: {
  (data: unknown) : boolean;
  errors: ErrorObject[] | null;
}
export = validate;
// This file is auto-generated by the validateSchemaPlugin.