import type { AudioFileParams } from "@RpgTypes/libs";
import type { Data_SystemMV } from "@RpgTypes/rmmz";
import type { JSONSchemaType, Schema } from "ajv";
import {
  SCHEMA_SYSTEM_VEHICLE,
  SCHEMA_SYSTEM_MEMBERS_ATTACK_MOTION,
  SCHEMA_SYSTEM_MENU_COMMANDS_ENABLED,
  SCHEMA_SYSTEM_MEMBERS_TERMS_COMMANDS_ARRAY,
  SCHEMA_SYSTEM_MEMBERS_TERMS_BASIC_ARRAY,
  SCHEMA_SYSTEM_PARAM_NAMS_ARRAY,
} from "./core";
import { SCHEMA_SYSTEM_TERMS_MESSAGES_MV } from "./core/trems/messageMV";
import { SCHEMA_SYSTEM_TEST_BATTLER } from "./gameEdit/testBattle";

export const SCHEMA_DATA_SYSTEM_MV = {
  additionalProperties: false,
  $defs: {
    Audio: {
      type: "object",
      required: ["name", "volume", "pitch", "pan"],
      additionalProperties: false,
      properties: {
        name: { type: "string" },
        volume: { type: "integer" },
        pitch: { type: "integer" },
        pan: { type: "integer" },
      },
    } as const satisfies JSONSchemaType<AudioFileParams>,
    Vehicle: SCHEMA_SYSTEM_VEHICLE,
    AttackMotion: SCHEMA_SYSTEM_MEMBERS_ATTACK_MOTION,
    TestBattler: SCHEMA_SYSTEM_TEST_BATTLER,
    MenuCommands: SCHEMA_SYSTEM_MENU_COMMANDS_ENABLED,
    TermsCommands: SCHEMA_SYSTEM_MEMBERS_TERMS_COMMANDS_ARRAY,
    TermsBasic: SCHEMA_SYSTEM_MEMBERS_TERMS_BASIC_ARRAY,
    TermsParams: SCHEMA_SYSTEM_PARAM_NAMS_ARRAY,
    TermsMessages: SCHEMA_SYSTEM_TERMS_MESSAGES_MV,
  },
  type: "object",
  required: [
    "gameTitle",
    "currencyUnit",
    "terms",
    "ship",
    "boat",
    "airship",
    "titleBgm",
    "battleBgm",
    "gameoverMe",
    "victoryMe",
    "defeatMe",
    "attackMotions",
    "optDisplayTp",
    "optFloorDeath",
    "optFollowers",
    "optSideView",
    "optSlipDeath",
    "optTransparent",
    "optDrawTitle",
    "optExtraExp",
    "startMapId",
    "startX",
    "startY",
    "elements",
    "weaponTypes",
    "armorTypes",
    "equipTypes",
    "skillTypes",
    "switches",
    "variables",
    "magicSkills",
    "battleback1Name",
    "battleback2Name",
    "testTroopId",
    "partyMembers",
    "testBattlers",
    "editMapId",
    "battlerHue",
    "battlerName",
    "sounds",
    "title1Name",
    "title2Name",
    "versionId",
    "locale",
    "windowTone",
    "menuCommands",
  ] satisfies Array<keyof Data_SystemMV>,
  properties: {
    gameTitle: { type: "string" },
    currencyUnit: { type: "string" },
    attackMotions: {
      items: { $ref: "#/$defs/AttackMotion" },
      type: "array",
    },
    titleBgm: { $ref: "#/$defs/Audio" },
    battleBgm: { $ref: "#/$defs/Audio" },
    gameoverMe: { $ref: "#/$defs/Audio" },
    victoryMe: { $ref: "#/$defs/Audio" },
    defeatMe: { $ref: "#/$defs/Audio" },
    sounds: {
      type: "array",
      maxItems: 24,
      minItems: 24,
      items: { $ref: "#/$defs/Audio" },
    },
    menuCommands: { $ref: "#/$defs/MenuCommands" },
    ship: { $ref: "#/$defs/Vehicle" },
    boat: { $ref: "#/$defs/Vehicle" },
    airship: { $ref: "#/$defs/Vehicle" },
    testBattlers: {
      type: "array",
      items: {
        $ref: "#/$defs/TestBattler",
      },
    },
    terms: {
      type: "object",
      additionalProperties: false,
      required: ["messages", "commands", "basic", "params"],
      properties: {
        messages: { $ref: "#/$defs/TermsMessages" },
        commands: { $ref: "#/$defs/TermsCommands" },
        basic: { $ref: "#/$defs/TermsBasic" },
        params: { $ref: "#/$defs/TermsParams" },
      },
    },
    optDisplayTp: { type: "boolean" },
    optFloorDeath: { type: "boolean" },
    optFollowers: { type: "boolean" },
    optSideView: { type: "boolean" },
    optSlipDeath: { type: "boolean" },
    optTransparent: { type: "boolean" },
    optDrawTitle: { type: "boolean" },
    optExtraExp: { type: "boolean" },
    startMapId: { type: "integer", minimum: 0 },
    startX: { type: "integer", minimum: 0 },
    startY: { type: "integer", minimum: 0 },
    elements: { type: "array", items: { type: "string" } },
    weaponTypes: { type: "array", items: { type: "string" } },
    armorTypes: { type: "array", items: { type: "string" } },
    equipTypes: { type: "array", items: { type: "string" } },
    skillTypes: { type: "array", items: { type: "string" } },
    switches: { type: "array", items: { type: "string" } },
    variables: { type: "array", items: { type: "string" } },
    magicSkills: { type: "array", items: { type: "integer" } },
    battleback1Name: { type: "string" },
    battleback2Name: { type: "string" },
    testTroopId: { type: "integer", minimum: 0 },
    partyMembers: {
      type: "array",
      items: { type: "integer" },
    },

    editMapId: { type: "integer", minimum: 0 },
    battlerHue: { type: "integer" },
    battlerName: { type: "string" },
    title1Name: { type: "string" },
    title2Name: { type: "string" },
    versionId: { type: "integer" },
    locale: { type: "string" },
    windowTone: {
      type: "array",
      items: { type: "integer", minimum: 0, maximum: 255 },
    },
  } satisfies Record<keyof Data_SystemMV, Schema>,
} as const satisfies Schema;
