import { describe, expect, test, vi } from "vitest";
import type { Terms_Messages } from "@RpgTypes/rmmz";
import { systemMessages } from "./systemTerms";
import type { ExtractedSystemMessageItem } from "./types";

type UUID = "test-uuid";
const MockUUID = "test-uuid" as const satisfies UUID;
const filename = "system.json" as const;

const mockMessage: Terms_Messages = {
  alwaysDash: "Always Dash",
  commandRemember: "Command Remember",
  touchUI: "Touch UI",
  bgmVolume: "BGM Volume",
  bgsVolume: "BGS Volume",
  meVolume: "ME Volume",
  seVolume: "SE Volume",
  possession: "Possession",
  expTotal: "Total EXP",
  expNext: "Next EXP",
  saveMessage: "Save Message",
  loadMessage: "Load Message",
  file: "File",
  autosave: "Autosave",
  partyName: "Party Name",
  emerge: "Emerge",
  preemptive: "Preemptive",
  surprise: "Surprise",
  escapeStart: "Escape Start",
  escapeFailure: "Escape Failure",
  victory: "Victory",
  defeat: "Defeat",
  obtainExp: "Obtain EXP",
  obtainGold: "Obtain Gold",
  obtainItem: "Obtain Item",
  levelUp: "Level Up!",
  obtainSkill: "Obtain Skill",
  useItem: "Use Item",
  criticalToEnemy: "Critical to Enemy",
  criticalToActor: "Critical to Actor",
  actorDamage: "Actor Damage",
  actorRecovery: "Actor Recovery",
  actorGain: "Actor Gain",
  actorLoss: "Actor Loss",
  actorDrain: "Actor Drain",
  actorNoDamage: "Actor No Damage",
  actorNoHit: "Actor No Hit",
  enemyDamage: "Enemy Damage",
  enemyRecovery: "Enemy Recovery",
  enemyGain: "Enemy Gain",
  enemyLoss: "Enemy Loss",
  enemyDrain: "Enemy Drain",
  enemyNoDamage: "Enemy No Damage",
  enemyNoHit: "Enemy No Hit",
  evasion: "Evasion",
  magicEvasion: "Magic Evasion",
  magicReflection: "Magic Reflection",
  counterAttack: "Counter Attack",
  substitute: "Substitute",
  buffAdd: "Buff Add",
  debuffAdd: "Debuff Add",
  buffRemove: "Buff Remove",
  actionFailure: "Action Failed",
};

const kindMessages: Terms_Messages = {
  alwaysDash: "常にダッシュ",
  commandRemember: "コマンド記憶",
  touchUI: "タッチUI",
  bgmVolume: "BGM音量",
  bgsVolume: "BGS音量",
  meVolume: "ME音量",
  seVolume: "SE音量",
  possession: "所持数",
  expTotal: "総経験値",
  expNext: "次の経験値",
  saveMessage: "セーブメッセージ",
  loadMessage: "ロードメッセージ",
  file: "ファイル",
  autosave: "オートセーブ",
  partyName: "パーティ名",
  emerge: "エンカウント",
  preemptive: "先制攻撃",
  surprise: "奇襲攻撃",
  escapeStart: "逃走開始",
  escapeFailure: "逃走失敗",
  victory: "勝利",
  defeat: "敗北",
  obtainExp: "経験値獲得",
  obtainGold: "ゴールド獲得",
  obtainItem: "アイテム獲得",
  levelUp: "レベルアップ",
  obtainSkill: "スキル習得",
  useItem: "アイテム使用",
  criticalToEnemy: "敵にクリティカル",
  criticalToActor: "味方にクリティカル",
  actorDamage: "味方ダメージ",
  actorRecovery: "味方回復",
  actorGain: "味方獲得",
  actorLoss: "味方損失",
  actorDrain: "味方吸収",
  actorNoDamage: "味方ノーダメージ",
  actorNoHit: "味方ノーヒット",
  enemyDamage: "敵ダメージ",
  enemyRecovery: "敵回復",
  enemyGain: "敵獲得",
  enemyLoss: "敵損失",
  enemyDrain: "敵吸収",
  enemyNoDamage: "敵ノーダメージ",
  enemyNoHit: "敵ノーヒット",
  evasion: "回避",
  magicEvasion: "魔法回避",
  magicReflection: "魔法反射",
  counterAttack: "カウンターアタック",
  substitute: "サブスティチュート",
  actionFailure: "行動失敗",
  buffAdd: "バフ追加",
  buffRemove: "バフ削除",
  debuffAdd: "デバフ追加",
};
const expectedMessages: ExtractedSystemMessageItem<UUID>[] = [
  {
    baseText: mockMessage.alwaysDash,
    filename,
    id: 0,
    kind: kindMessages.alwaysDash,
    uuid: "test-uuid",
    dataKey: "messages.alwaysDash",
  },
  {
    baseText: mockMessage.commandRemember,
    filename,
    id: 0,
    kind: kindMessages.commandRemember,
    uuid: "test-uuid",
    dataKey: "messages.commandRemember",
  },
  {
    baseText: mockMessage.touchUI,
    filename,
    id: 0,
    kind: kindMessages.touchUI,
    uuid: "test-uuid",
    dataKey: "messages.touchUI",
  },
  {
    baseText: mockMessage.bgmVolume,
    filename,
    id: 0,
    kind: kindMessages.bgmVolume,
    uuid: "test-uuid",
    dataKey: "messages.bgmVolume",
  },
  {
    baseText: mockMessage.bgsVolume,
    filename,
    id: 0,
    kind: kindMessages.bgsVolume,
    uuid: "test-uuid",
    dataKey: "messages.bgsVolume",
  },
  {
    baseText: mockMessage.meVolume,
    filename,
    id: 0,
    kind: kindMessages.meVolume,
    uuid: "test-uuid",
    dataKey: "messages.meVolume",
  },
  {
    baseText: mockMessage.seVolume,
    filename,
    id: 0,
    kind: kindMessages.seVolume,
    uuid: "test-uuid",
    dataKey: "messages.seVolume",
  },
  {
    baseText: mockMessage.possession,
    dataKey: "messages.possession",
    filename: "system.json",
    id: 0,
    kind: "所持数",
    uuid: "test-uuid",
  },
  {
    baseText: "Total EXP",
    dataKey: "messages.expTotal",
    filename: "system.json",
    id: 0,
    kind: "総経験値",
    uuid: "test-uuid",
  },
  {
    baseText: "Next EXP",
    dataKey: "messages.expNext",
    filename: "system.json",
    id: 0,
    kind: "次の経験値",
    uuid: "test-uuid",
  },
  {
    baseText: "Save Message",
    dataKey: "messages.saveMessage",
    filename: "system.json",
    id: 0,
    kind: "セーブメッセージ",
    uuid: "test-uuid",
  },
  {
    baseText: "Load Message",
    dataKey: "messages.loadMessage",
    filename: "system.json",
    id: 0,
    kind: "ロードメッセージ",
    uuid: "test-uuid",
  },
  {
    baseText: "File",
    dataKey: "messages.file",
    filename: "system.json",
    id: 0,
    kind: "ファイル",
    uuid: "test-uuid",
  },
  {
    baseText: "Autosave",
    dataKey: "messages.autosave",
    filename: "system.json",
    id: 0,
    kind: "オートセーブ",
    uuid: "test-uuid",
  },
  {
    baseText: "Party Name",
    dataKey: "messages.partyName",
    filename: "system.json",
    id: 0,
    kind: "パーティ名",
    uuid: "test-uuid",
  },
  {
    baseText: "Emerge",
    dataKey: "messages.emerge",
    filename: "system.json",
    id: 0,
    kind: "エンカウント",
    uuid: "test-uuid",
  },
  {
    baseText: "Preemptive",
    dataKey: "messages.preemptive",
    filename: "system.json",
    id: 0,
    kind: "先制攻撃",
    uuid: "test-uuid",
  },
  {
    baseText: "Surprise",
    dataKey: "messages.surprise",
    filename: "system.json",
    id: 0,
    kind: "奇襲攻撃",
    uuid: "test-uuid",
  },
  {
    baseText: "Escape Start",
    dataKey: "messages.escapeStart",
    filename: "system.json",
    id: 0,
    kind: "逃走開始",
    uuid: "test-uuid",
  },
  {
    baseText: "Escape Failure",
    dataKey: "messages.escapeFailure",
    filename: "system.json",
    id: 0,
    kind: "逃走失敗",
    uuid: "test-uuid",
  },
  {
    baseText: "Victory",
    dataKey: "messages.victory",
    filename: "system.json",
    id: 0,
    kind: "勝利",
    uuid: "test-uuid",
  },
  {
    baseText: "Defeat",
    dataKey: "messages.defeat",
    filename: "system.json",
    id: 0,
    kind: "敗北",
    uuid: "test-uuid",
  },
  {
    baseText: "Obtain EXP",
    dataKey: "messages.obtainExp",
    filename: "system.json",
    id: 0,
    kind: "経験値獲得",
    uuid: "test-uuid",
  },
  {
    baseText: "Obtain Gold",
    dataKey: "messages.obtainGold",
    filename: "system.json",
    id: 0,
    kind: "ゴールド獲得",
    uuid: "test-uuid",
  },
  {
    baseText: "Obtain Item",
    dataKey: "messages.obtainItem",
    filename: "system.json",
    id: 0,
    kind: "アイテム獲得",
    uuid: "test-uuid",
  },
  {
    baseText: "Level Up!",
    dataKey: "messages.levelUp",
    filename: "system.json",
    id: 0,
    kind: "レベルアップ",
    uuid: "test-uuid",
  },
  {
    baseText: "Obtain Skill",
    dataKey: "messages.obtainSkill",
    filename: "system.json",
    id: 0,
    kind: "スキル習得",
    uuid: "test-uuid",
  },
  {
    baseText: "Use Item",
    dataKey: "messages.useItem",
    filename: "system.json",
    id: 0,
    kind: "アイテム使用",
    uuid: "test-uuid",
  },
  {
    baseText: "Critical to Enemy",
    dataKey: "messages.criticalToEnemy",
    filename: "system.json",
    id: 0,
    kind: "敵にクリティカル",
    uuid: "test-uuid",
  },
  {
    baseText: "Critical to Actor",
    dataKey: "messages.criticalToActor",
    filename: "system.json",
    id: 0,
    kind: "味方にクリティカル",
    uuid: "test-uuid",
  },
  {
    baseText: "Actor Damage",
    dataKey: "messages.actorDamage",
    filename: "system.json",
    id: 0,
    kind: "味方ダメージ",
    uuid: "test-uuid",
  },
  {
    baseText: "Actor Recovery",
    dataKey: "messages.actorRecovery",
    filename: "system.json",
    id: 0,
    kind: "味方回復",
    uuid: "test-uuid",
  },
  {
    baseText: "Actor Gain",
    dataKey: "messages.actorGain",
    filename: "system.json",
    id: 0,
    kind: "味方獲得",
    uuid: "test-uuid",
  },
  {
    baseText: "Actor Loss",
    dataKey: "messages.actorLoss",
    filename: "system.json",
    id: 0,
    kind: "味方損失",
    uuid: "test-uuid",
  },
  {
    baseText: "Actor Drain",
    dataKey: "messages.actorDrain",
    filename: "system.json",
    id: 0,
    kind: "味方吸収",
    uuid: "test-uuid",
  },
  {
    baseText: "Actor No Damage",
    dataKey: "messages.actorNoDamage",
    filename: "system.json",
    id: 0,
    kind: "味方ノーダメージ",
    uuid: "test-uuid",
  },
  {
    baseText: "Actor No Hit",
    dataKey: "messages.actorNoHit",
    filename: "system.json",
    id: 0,
    kind: "味方ノーヒット",
    uuid: "test-uuid",
  },
  {
    baseText: "Enemy Damage",
    dataKey: "messages.enemyDamage",
    filename: "system.json",
    id: 0,
    kind: "敵ダメージ",
    uuid: "test-uuid",
  },
  {
    baseText: "Enemy Recovery",
    dataKey: "messages.enemyRecovery",
    filename: "system.json",
    id: 0,
    kind: "敵回復",
    uuid: "test-uuid",
  },
  {
    baseText: "Enemy Gain",
    dataKey: "messages.enemyGain",
    filename: "system.json",
    id: 0,
    kind: "敵獲得",
    uuid: "test-uuid",
  },
  {
    baseText: "Enemy Loss",
    dataKey: "messages.enemyLoss",
    filename: "system.json",
    id: 0,
    kind: "敵損失",
    uuid: "test-uuid",
  },
  {
    baseText: "Enemy Drain",
    dataKey: "messages.enemyDrain",
    filename: "system.json",
    id: 0,
    kind: "敵吸収",
    uuid: "test-uuid",
  },
  {
    baseText: "Enemy No Damage",
    dataKey: "messages.enemyNoDamage",
    filename: "system.json",
    id: 0,
    kind: "敵ノーダメージ",
    uuid: "test-uuid",
  },
  {
    baseText: "Enemy No Hit",
    dataKey: "messages.enemyNoHit",
    filename: "system.json",
    id: 0,
    kind: "敵ノーヒット",
    uuid: "test-uuid",
  },
  {
    baseText: "Evasion",
    dataKey: "messages.evasion",
    filename: "system.json",
    id: 0,
    kind: "回避",
    uuid: "test-uuid",
  },
  {
    baseText: "Magic Evasion",
    dataKey: "messages.magicEvasion",
    filename: "system.json",
    id: 0,
    kind: "魔法回避",
    uuid: "test-uuid",
  },
  {
    baseText: "Magic Reflection",
    dataKey: "messages.magicReflection",
    filename: "system.json",
    id: 0,
    kind: "魔法反射",
    uuid: "test-uuid",
  },
  {
    baseText: "Counter Attack",
    dataKey: "messages.counterAttack",
    filename: "system.json",
    id: 0,
    kind: "カウンターアタック",
    uuid: "test-uuid",
  },
  {
    baseText: "Substitute",
    dataKey: "messages.substitute",
    filename: "system.json",
    id: 0,
    kind: "サブスティチュート",
    uuid: "test-uuid",
  },
  {
    baseText: "Buff Add",
    dataKey: "messages.buffAdd",
    filename: "system.json",
    id: 0,
    kind: "バフ追加",
    uuid: "test-uuid",
  },
  {
    baseText: "Debuff Add",
    dataKey: "messages.debuffAdd",
    filename: "system.json",
    id: 0,
    kind: "デバフ追加",
    uuid: "test-uuid",
  },
  {
    baseText: "Buff Remove",
    dataKey: "messages.buffRemove",
    filename: "system.json",
    id: 0,
    kind: "バフ削除",
    uuid: "test-uuid",
  },
  {
    baseText: "Action Failed",
    dataKey: "messages.actionFailure",
    filename: "system.json",
    id: 0,
    kind: "行動失敗",
    uuid: "test-uuid",
  },
];
describe("systemMessages", () => {
  const mockFnUUID = vi.fn(() => MockUUID);
  const kindFn = vi.fn<(key: keyof Terms_Messages) => string>(
    (key) => kindMessages[key],
  );
  const result = systemMessages<UUID>(
    mockMessage,
    filename,
    mockFnUUID,
    kindFn,
  );

  test("should extract system messages", () => {
    expect(result).toEqual(expectedMessages);
  });
  test("should call UUID function for each message", () => {
    expect(mockFnUUID).toHaveBeenCalledTimes(expectedMessages.length);
  });
  test("messages handler should be called once for each message key", () => {
    const calledKeys = new Set<string>(
      kindFn.mock.calls.map((call) => call[0]),
    );
    expect(calledKeys.size).toBe(Object.keys(mockMessage).length);
    expect(calledKeys).toEqual(new Set(Object.keys(mockMessage)));
  });
});
