import {
  SHOW_MESSAGE,
  SHOW_CHOICES,
  SHOW_CHOICES_ITEM,
  SHOW_SCROLLING_TEXT,
  SHOW_SCROLLING_TEXT_BODY,
  SHOW_PICTURE,
  MOVE_PICTURE,
  SHOW_BALLOON_ICON,
  SHOW_ANIMATION,
  SHOW_MESSAGE_BODY,
  BATTLE_PROCESSING,
  CHANGE_ACTOR_IMAGES,
  CHANGE_ARMORS,
  CHANGE_BATTLE_BACKGROUND,
  CHANGE_BATTLE_BGM,
  CHANGE_CLASS,
  CHANGE_DEFEAT_ME,
  CHANGE_ENCOUNTER,
  CHANGE_ENEMY_HP,
  CHANGE_ENEMY_MP,
  CHANGE_FORMATION_ACCESS,
  CHANGE_GOLD,
  CHANGE_ITEMS,
  CHANGE_MENU_ACCESS,
  CHANGE_MP,
  CHANGE_NAME,
  CHANGE_NICKNAME,
  CHANGE_PARALLAX,
  CHANGE_PARTY_MEMBER,
  CHANGE_PLAYER_FOLLOWERS,
  CHANGE_PROFILE,
  CHANGE_SAVE_ACCESS,
  CHANGE_TILESET,
  CHANGE_TRANSPARENCY,
  CHANGE_VEHICLE_BGM,
  CHANGE_VEHICLE_IMAGE,
  CHANGE_VICTORY_ME,
  CHANGE_WEAPONS,
  CHANGE_WINDOW_COLOR,
  CONDITIONAL_BRANCH,
  CONDITIONAL_BRANCH_ELSE,
  COMMENT_HEAD,
  COMMENT_BODY,
  SHOP_PROCESSING_BODY,
  SCRIPT_EVAL,
  SCRIPT_EVAL_BODY,
  SCROLL_MAP,
  SET_EVENT_LOCATION,
  SET_MOVEMENT_ROUTE,
  SET_VEHICLE_LOCATION,
  SELECT_ITEM,
  SET_WEATHER_EFFECT,
  SAVE_BGM,
} from "@RpgTypes/libs/eventCommand";
import type { EventCommandTable, EventCode } from "@RpgTypes/rmmz";

interface VV {
  name: Extract<keyof EventCommandTable, string>;
}

const TABLE = {
  [SHOW_MESSAGE]: { name: "showMessage" },
  [SHOW_CHOICES]: { name: "showChoices" },
  [SHOW_CHOICES_ITEM]: { name: "showChoicesItem" },
  [SHOW_SCROLLING_TEXT]: { name: "showScrollingText" },
  [SHOW_SCROLLING_TEXT_BODY]: { name: "showScrollingTextBody" },
  [SHOW_PICTURE]: { name: "showPicture" },
  [MOVE_PICTURE]: { name: "movePicture" },
  [SHOW_BALLOON_ICON]: { name: "showBalloonIcon" },
  [SHOW_ANIMATION]: { name: "showAnimation" },
  [SHOW_MESSAGE_BODY]: { name: "showMessageBody" },
  [BATTLE_PROCESSING]: { name: "battleProcessing" },
  [CHANGE_ACTOR_IMAGES]: { name: "changeActorImages" },
  [CHANGE_ARMORS]: { name: "changeArmors" },
  [CHANGE_BATTLE_BACKGROUND]: { name: "changeBattleBackground" },
  [CHANGE_BATTLE_BGM]: { name: "changeBattleBgm" },
  [CHANGE_CLASS]: { name: "changeClass" },
  [CHANGE_DEFEAT_ME]: { name: "changeDefeatMe" },
  [CHANGE_ENCOUNTER]: { name: "changeEncounter" },
  [CHANGE_ENEMY_HP]: { name: "changeEnemyHp" },
  [CHANGE_ENEMY_MP]: { name: "changeEnemyMp" },
  [CHANGE_FORMATION_ACCESS]: { name: "changeFormationAccess" },
  [CHANGE_GOLD]: { name: "changeGold" },
  [CHANGE_ITEMS]: { name: "changeItems" },
  [CHANGE_MENU_ACCESS]: { name: "changeMenuAccess" },
  [CHANGE_MP]: { name: "changeMp" },
  [CHANGE_NAME]: { name: "changeName" },
  [CHANGE_NICKNAME]: { name: "changeNickname" },
  [CHANGE_PARALLAX]: { name: "changeParallax" },
  [CHANGE_PARTY_MEMBER]: { name: "changePartyMember" },
  [CHANGE_PLAYER_FOLLOWERS]: { name: "changePlayerFollowers" },
  [CHANGE_PROFILE]: { name: "changeProfile" },
  [CHANGE_SAVE_ACCESS]: { name: "changeSaveAccess" },
  [CHANGE_TILESET]: { name: "changeTileset" },
  [CHANGE_TRANSPARENCY]: { name: "changeTransparency" },
  [CHANGE_VEHICLE_BGM]: { name: "changeVehicleBgm" },
  [CHANGE_VEHICLE_IMAGE]: { name: "changeVehicleImage" },
  [CHANGE_VICTORY_ME]: { name: "changeVictoryMe" },
  [CHANGE_WEAPONS]: { name: "changeWeapons" },
  [CHANGE_WINDOW_COLOR]: { name: "changeWindowColor" },
  [CONDITIONAL_BRANCH]: { name: "conditionalBranch" },
  [CONDITIONAL_BRANCH_ELSE]: { name: "conditionalBranchElse" },
  [COMMENT_HEAD]: { name: "commentHead" },
  [COMMENT_BODY]: { name: "commentBody" },
  [SHOP_PROCESSING_BODY]: { name: "shopProcessingBody" },
  [SCRIPT_EVAL]: { name: "scriptEval" },
  [SCRIPT_EVAL_BODY]: { name: "scriptEvalBody" },
  [SCROLL_MAP]: { name: "scrollMap" },
  [SET_EVENT_LOCATION]: { name: "setEventLocation" },
  [SET_MOVEMENT_ROUTE]: { name: "setMovementRoute" },
  [SET_VEHICLE_LOCATION]: { name: "setVehicleLocation" },
  [SELECT_ITEM]: { name: "selectItem" },
  [SET_WEATHER_EFFECT]: { name: "setWeatherEffect" },
  [SAVE_BGM]: { name: "saveBgm" },
} as const satisfies Partial<Record<EventCode, VV>>;
