import type { LabelRegistry } from "./labelRegistry";
import { DEFAULT_GLOBAL_LABELS } from "./labelUtils";
import {
  DEFAULT_ACTOR_LABELS,
  DEFAULT_ARMOR_LABELS,
  DEFAULT_CLASS_LABELS,
  LABELS_COLLAPS,
  DEFAULT_DAMAGE_LABELS,
  DEFAULT_EFFECT_LABELS_SET,
  DEFAULT_ENEMY_LABELS,
  DEFAULT_ITEM_LABELS,
  LABELS_PARAM_REGULAR,
  LABELS_PARAM_SPECIAL,
  LABELS_PARTY_ABILITY,
  DEFAULT_SKILL_LABELS,
  LABELS_TRAIT_SPECIALFLAG,
  DEFAULT_STATE_LABELS,
  DEFAULT_USABLE_ITEM_LABELS,
  DEFAULT_WEAPON_LABELS,
  LABELS_EXTRA_PARAM,
} from "./data";

export const LABEL_REGISTRY_JP = {
  rpg: {
    actor: DEFAULT_ACTOR_LABELS,

    armor: DEFAULT_ARMOR_LABELS,
    skill: DEFAULT_SKILL_LABELS,
    damage: DEFAULT_DAMAGE_LABELS,
    item: DEFAULT_ITEM_LABELS,
    weapon: DEFAULT_WEAPON_LABELS,
    enemy: DEFAULT_ENEMY_LABELS,
    state: DEFAULT_STATE_LABELS,
    paramSpecial: LABELS_PARAM_SPECIAL,
    paramRegular: LABELS_PARAM_REGULAR,
    paramExtra: LABELS_EXTRA_PARAM,
    collaps: LABELS_COLLAPS,
    specialFlag: LABELS_TRAIT_SPECIALFLAG,
    partyAbility: LABELS_PARTY_ABILITY,
    class: DEFAULT_CLASS_LABELS,
    usableItem: DEFAULT_USABLE_ITEM_LABELS,
    itemEffect: DEFAULT_EFFECT_LABELS_SET,
  },
  global: DEFAULT_GLOBAL_LABELS,
} as const satisfies LabelRegistry;
