import type { LabelRegistry } from "./labelRegistry";
import { DEFAULT_GLOBAL_LABELS } from "./labelUtils";
import {
  DEFAULT_ACTOR_LABELS,
  DEFAULT_ARMOR_LABELS,
  DEFAULT_CLASS_LABELS,
  DEFAULT_COLLAPS_LABELS,
  DEFAULT_DAMAGE_LABELS,
  DEFAULT_ENEMY_LABELS,
  DEFAULT_ITEM_LABELS,
  DEFAULT_PARAMREGULAR_LABELS,
  DEFAULT_PARAMSPECIAL_LABELS,
  DEFAULT_PARTY_ABILITY_LABELS,
  DEFAULT_SKILL_LABELS,
  DEFAULT_SPECIALFLAG_LABELS,
  DEFAULT_STATE_LABELS,
  DEFAULT_USABLE_ITEM_LABELS,
  DEFAULT_WEAPON_LABELS,
  DEFUALT_EXTRA_PARAM_LABELS,
} from "./data";

export const LABEL_REGISTRY_JP = {
  rpg: {
    actor: DEFAULT_ACTOR_LABELS,

    armor: DEFAULT_ARMOR_LABELS,
    skill: DEFAULT_SKILL_LABELS,
    damage: DEFAULT_DAMAGE_LABELS,
    item: DEFAULT_ITEM_LABELS,
    weapon: DEFAULT_WEAPON_LABELS,
    enemy: DEFAULT_ENEMY_LABELS,
    state: DEFAULT_STATE_LABELS,
    paramSpecial: DEFAULT_PARAMSPECIAL_LABELS,
    paramRegular: DEFAULT_PARAMREGULAR_LABELS,
    paramExtra: DEFUALT_EXTRA_PARAM_LABELS,
    collaps: DEFAULT_COLLAPS_LABELS,
    specialFlag: DEFAULT_SPECIALFLAG_LABELS,
    partyAbility: DEFAULT_PARTY_ABILITY_LABELS,
    class: DEFAULT_CLASS_LABELS,
    usableItem: DEFAULT_USABLE_ITEM_LABELS,
  },
  global: DEFAULT_GLOBAL_LABELS,
} as const satisfies LabelRegistry;
