import type { Game_Actors } from "./Game_Actors";
import type { Game_Map } from "./Game_Map";
import type { Game_Message } from "./Game_Message";
import type { Game_Party } from "./Game_Party";
import type { Game_Player } from "./Game_Player";
import type { Game_Screen } from "./Game_Screen";
import type { Game_SelfSwitches } from "./Game_SelfSwitches";
import type { Game_Switches } from "./Game_Switches";
import type { Game_System } from "./Game_System";
import type { Game_Temp } from "./Game_Temp";
import type { Game_Timer } from "./Game_Timer";
import type { Game_Troop } from "./Game_Troop";
import type { Game_Variables } from "./Game_Variables";

export declare let $gameTemp: Game_Temp;
export declare let $gameSystem: Game_System;
export declare let $gameScreen: Game_Screen;
export declare let $gameTimer: Game_Timer;
export declare let $gameMessage: Game_Message;
export declare let $gameSwitches: Game_Switches;
export declare let $gameVariables: Game_Variables;
export declare let $gameSelfSwitches: Game_SelfSwitches;
export declare let $gameActors: Game_Actors;
export declare let $gameParty: Game_Party;
export declare let $gameTroop: Game_Troop;
export declare let $gameMap: Game_Map;
export declare let $gamePlayer: Game_Player;
