import { describe, test, expect } from "vitest";
import type { SystemTexts } from "@RpgTypes/rmmz";
import { isSystemTexts } from "./isSystemTexts";
const systemTexts: SystemTexts = {
  gameTitle: "Test Game",
  currencyUnit: "Gold",
  equipTypes: ["Sword", "Shield"],
  armorTypes: ["Helmet", "Armor"],
  weaponTypes: ["Sword", "Axe"],
  elements: ["Fire", "Water"],
  skillTypes: ["Magic", "Physical"],
  terms: {
    basic: {
      level: "Level",
      hp: "HP",
      mp: "MP",
      tp: "TP",
      levelA: "Lv.",
      hpA: "HP",
      mpA: "MP",
      tpA: "TP",
      experience: "EXP",
      exp: "EXP",
    },
    commands: {
      fight: "Fight",
      escape: "Escape",
      attack: "Attack",
      guard: "Guard",
      item: "Item",
      skill: "Skill",
      equip: "Equip",
      status: "Status",
      formation: "Formation",
      save: "Save",
      gameEnd: "Game End",
      options: "Options",
      weapon: "Weapon",
      armor: "Armor",
      keyItem: "Key Item",
      equip2: "Equip",
      optimize: "Optimize",
      clear: "Clear",
      newGame: "New Game",
      continueGame: "Continue",
      toTitle: "To Title",
      cancel: "Cancel",
      buy: "Buy",
      sell: "Sell",
    },
    params: {
      mhp: "Max HP",
      mmp: "Max MP",
      atk: "Attack",
      def: "Defense",
      mat: "Magic Attack",
      mdf: "Magic Defense",
      agi: "Agility",
      luk: "Luck",
      hit: "Hit",
      eva: "Evasion",
    },
    messages: {
      actionFailure: "Action Failure",
      actorDamage: "Actor Damage",
      actorNoDamage: "Actor No Damage",
      actorRecovery: "Actor Recovery",
      actorNoHit: "Actor No Hit",
      actorDrain: "Actor Drain",
      actorGain: "Actor Gain",
      actorLoss: "Actor Loss",
      enemyDamage: "Enemy Damage",
      enemyNoDamage: "Enemy No Damage",
      enemyRecovery: "Enemy Recovery",
      enemyNoHit: "Enemy No Hit",
      enemyDrain: "Enemy Drain",
      enemyGain: "Enemy Gain",
      enemyLoss: "Enemy Loss",
      levelUp: "Level Up!",
      victory: "Victory!",
      alwaysDash: "Always Dash",
      autosave: "Autosave",
      escapeStart: "Escape Start",
      bgmVolume: "BGM Volume",
      bgsVolume: "BGS Volume",
      meVolume: "ME Volume",
      buffAdd: "Buff Add",
      buffRemove: "Buff Remove",
      commandRemember: "Command Remember",
      counterAttack: "Counter Attack",
      criticalToActor: "Critical To Actor",
      criticalToEnemy: "Critical To Enemy",
      debuffAdd: "Debuff Add",
      defeat: "Defeat",
      evasion: "Evasion",
      escapeFailure: "Escape Failure",
      emerge: "Emerge",
      preemptive: "Preemptive",
      surprise: "Surprise",
      expNext: "EXP Next",
      expTotal: "EXP Total",
      file: "File",
      loadMessage: "Load Message",
      partyName: "Party Name",
      magicEvasion: "Magic Evasion",
      magicReflection: "Magic Reflection",
      obtainExp: "Obtain EXP",
      obtainGold: "Obtain Gold",
      obtainItem: "Obtain Item",
      obtainSkill: "Obtain Skill",
      possession: "Possession",
      saveMessage: "Save Message",
      seVolume: "SE Volume",
      substitute: "Substitute",
      touchUI: "Touch UI",
      useItem: "Use Item",
    },
  },
};

describe("isSystemTexts", () => {
  test("valid system texts", () => {
    const result = isSystemTexts(systemTexts);
    expect(result).toBe(true);
  });
  test("invalid system texts", () => {
    const reuslt = isSystemTexts({});
    expect(reuslt).toBe(false);
  });
});
