import type { SystemTexts } from "@RpgTypes/rmmz";
import type { JSONSchemaType } from "ajv";

export const SCHEMA_SYSTEM_TEXTS = {
  type: "object",
  required: [
    "gameTitle",
    "currencyUnit",
    "equipTypes",
    "armorTypes",
    "weaponTypes",
    "elements",
    "skillTypes",
    "terms",
  ],
  properties: {
    gameTitle: { type: "string" },
    currencyUnit: { type: "string" },
    equipTypes: {
      type: "array",
      items: { type: "string" },
    },
    armorTypes: {
      type: "array",
      items: { type: "string" },
    },
    weaponTypes: {
      type: "array",
      items: { type: "string" },
    },
    elements: {
      type: "array",
      items: { type: "string" },
    },
    skillTypes: {
      type: "array",
      items: { type: "string" },
    },
    terms: {
      type: "object",
      required: ["basic", "commands", "messages", "params"],
      properties: {
        basic: {
          type: "object",
          required: [
            "level",
            "hp",
            "mp",
            "tp",
            "levelA",
            "hpA",
            "mpA",
            "tpA",
            "experience",
            "exp",
          ],
          properties: {
            level: { type: "string" },
            hp: { type: "string" },
            mp: { type: "string" },
            tp: { type: "string" },
            levelA: { type: "string" },
            hpA: { type: "string" },
            mpA: { type: "string" },
            tpA: { type: "string" },
            experience: { type: "string" },
            exp: { type: "string" },
          },
        },
        commands: {
          type: "object",
          required: [
            "fight",
            "escape",
            "attack",
            "guard",
            "item",
            "skill",
            "equip",
            "status",
            "formation",
            "save",
            "gameEnd",
            "options",
            "weapon",
            "armor",
            "cancel",
            "clear",
            "continueGame",
            "toTitle",
            "sell",
            "keyItem",
            "equip2",
            "optimize",
            "newGame",
            "buy",
          ],
          properties: {
            fight: { type: "string" },
            escape: { type: "string" },
            attack: { type: "string" },
            guard: { type: "string" },
            item: { type: "string" },
            skill: { type: "string" },
            equip: { type: "string" },
            status: { type: "string" },
            formation: { type: "string" },
            save: { type: "string" },
            gameEnd: { type: "string" },
            options: { type: "string" },
            weapon: { type: "string" },
            armor: { type: "string" },
            cancel: { type: "string" },
            clear: { type: "string" },
            continueGame: { type: "string" },
            toTitle: { type: "string" },
            sell: { type: "string" },
            keyItem: { type: "string" },
            equip2: { type: "string" },
            optimize: { type: "string" },
            newGame: { type: "string" },
            buy: { type: "string" },
          },
        },
        messages: {
          type: "object",
          required: [
            "actorDamage",
            "actorGain",
            "actorLoss",
            "actorDrain",
            "enemyDamage",
            "enemyRecovery",
            "enemyGain",
            "enemyLoss",
            "enemyDrain",
            "touchUI",
            "autosave",
            "alwaysDash",
            "commandRemember",
            "bgmVolume",
            "bgsVolume",
            "meVolume",
            "seVolume",
            "possession",
            "expTotal",
            "expNext",
            "saveMessage",
            "loadMessage",
            "file",
            "partyName",
            "emerge",
            "preemptive",
            "surprise",
            "escapeStart",
            "escapeFailure",
            "victory",
            "defeat",
            "obtainExp",
            "obtainGold",
            "obtainItem",
            "obtainSkill",
            "levelUp",
            "useItem",
            "criticalToEnemy",
            "criticalToActor",
            "actorRecovery",
            "actorNoDamage",
            "actorNoHit",
            "enemyNoDamage",
            "enemyNoHit",
            "evasion",
            "magicEvasion",
            "magicReflection",
            "counterAttack",
            "substitute",
            "buffAdd",
            "debuffAdd",
            "buffRemove",
            "actionFailure",
          ],
          properties: {
            hpRecover: { type: "string" },
            mpRecover: { type: "string" },
            tpRecover: { type: "string" },
            actorDamage: { type: "string" },
            actorRecover: { type: "string" },
            actorGain: { type: "string" },
            actorLoss: { type: "string" },
            actorDrain: { type: "string" },
            enemyDamage: { type: "string" },
            enemyRecover: { type: "string" },
            enemyGain: { type: "string" },
            enemyLoss: { type: "string" },
            enemyDrain: { type: "string" },
            critical: { type: "string" },
            touchUI: { type: "string" },
            autosave: { type: "string" },
            alwaysDash: { type: "string" },
            commandRemember: { type: "string" },
            bgmVolume: { type: "string" },
            bgsVolume: { type: "string" },
            meVolume: { type: "string" },
            seVolume: { type: "string" },
            possession: { type: "string" },
            expTotal: { type: "string" },
            expNext: { type: "string" },
            saveMessage: { type: "string" },
            loadMessage: { type: "string" },
            file: { type: "string" },
            partyName: { type: "string" },
            emerge: { type: "string" },
            preemptive: { type: "string" },
            surprise: { type: "string" },
            escapeStart: { type: "string" },
            escapeFailure: { type: "string" },
            victory: { type: "string" },
            defeat: { type: "string" },
            obtainExp: { type: "string" },
            obtainGold: { type: "string" },
            obtainItem: { type: "string" },
            obtainSkill: { type: "string" },
            levelUp: { type: "string" },
            useItem: { type: "string" },
            criticalToEnemy: { type: "string" },
            criticalToActor: { type: "string" },
            actorRecovery: { type: "string" },
            actorNoDamage: { type: "string" },
            actorNoHit: { type: "string" },
            enemyNoDamage: { type: "string" },
            enemyNoHit: { type: "string" },
            enemyRecovery: { type: "string" },
            evasion: { type: "string" },
            magicEvasion: { type: "string" },
            magicReflection: { type: "string" },
            counterAttack: { type: "string" },
            substitute: { type: "string" },
            buffAdd: { type: "string" },
            debuffAdd: { type: "string" },
            buffRemove: { type: "string" },
            actionFailure: { type: "string" },
          },
        },
        params: {
          type: "object",
          required: [
            "mhp",
            "mmp",
            "atk",
            "def",
            "mat",
            "mdf",
            "agi",
            "luk",
            "hit",
            "eva",
          ],
          properties: {
            mhp: { type: "string" },
            mmp: { type: "string" },
            atk: { type: "string" },
            def: { type: "string" },
            mat: { type: "string" },
            mdf: { type: "string" },
            agi: { type: "string" },
            luk: { type: "string" },
            hit: { type: "string" },
            eva: { type: "string" },
          },
        },
      },
    },
  },
} as const satisfies JSONSchemaType<SystemTexts>;
